"""Models package — canonical SQLAlchemy models (models.py)"""

# Note: importing all models here in package init can cause SQLAlchemy declarative class
# conflicts when app imports models from another schema source (e.g., db.schema). Keep
# this minimal to avoid duplicate table warning in mixed environments.

from backend.app.models.models import (AuditLog,  # Pydantic schemas
                                       BankTransaction,
                                       BankTransactionCreateSchema,
                                       BankTransactionSchema, Base,
                                       ChartOfAccount, Employee,
                                       EmployeeCreateSchema, EmployeeSchema,
                                       Entity, EntityCreateSchema,
                                       EntitySchema, FixedAsset,
                                       FixedAssetCreateSchema,
                                       FixedAssetSchema, GSTReturn,
                                       GSTReturnCreateSchema, GSTReturnSchema,
                                       Inventory, InventoryCreateSchema,
                                       InventorySchema, Invoice,
                                       InvoiceCreateSchema, InvoiceSchema,
                                       JournalEntry, JournalEntryCreateSchema,
                                       JournalEntrySchema, JournalLine, Loan,
                                       LoanCreateSchema, LoanSchema,
                                       PayrollRun, PayrollRunCreateSchema,
                                       PayrollRunSchema, Portfolio,
                                       PortfolioCreateSchema, PortfolioSchema,
                                       QuantumJob, QuantumJobSchema)

__all__ = [
    "Base",
    "Entity",
    "ChartOfAccount",
    "JournalEntry",
    "JournalLine",
    "BankTransaction",
    "Invoice",
    "FixedAsset",
    "Inventory",
    "Employee",
    "PayrollRun",
    "Loan",
    "Portfolio",
    "AuditLog",
    "QuantumJob",
    "GSTReturn",
    "EntitySchema",
    "EntityCreateSchema",
    "JournalEntrySchema",
    "JournalEntryCreateSchema",
    "InvoiceSchema",
    "InvoiceCreateSchema",
    "BankTransactionSchema",
    "BankTransactionCreateSchema",
    "FixedAssetSchema",
    "FixedAssetCreateSchema",
    "InventorySchema",
    "InventoryCreateSchema",
    "EmployeeSchema",
    "EmployeeCreateSchema",
    "PayrollRunSchema",
    "PayrollRunCreateSchema",
    "LoanSchema",
    "LoanCreateSchema",
    "PortfolioSchema",
    "PortfolioCreateSchema",
    "QuantumJobSchema",
    "GSTReturnSchema",
    "GSTReturnCreateSchema",
]
