apiVersion: v1
kind: Service
metadata:
  name: {{ include "spoorthy-erp.fullname" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "spoorthy-erp.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
