apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spoorthy-erp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - spoorthy.local
      secretName: spoorthy-tls
  rules:
    - host: spoorthy.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spoorthy-erp
                port:
                  number: 80
