"""add_company_profile_and_order_fields

Revision ID: 071b2f9b5b8c
Revises: f3d0ba196e04
Create Date: 2026-04-01 01:39:00.937704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071b2f9b5b8c'
down_revision: Union[str, None] = 'f3d0ba196e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('bank_details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('item_description', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('hsn_code', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'hsn_code')
    op.drop_column('orders', 'item_description')
    op.drop_table('company_profile')
    # ### end Alembic commands ###
