"""create_orders_table

Revision ID: 792ff300ec7c
Revises: 
Create Date: 2026-04-01 00:43:06.608013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792ff300ec7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group_type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('affects_gross', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['account_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_account_groups_code'), 'account_groups', ['code'], unique=True)
    op.create_table('audit_trail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_uid', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('pqc_signature', sa.String(length=100), nullable=True),
    sa.Column('performed_by', sa.String(length=50), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_table_record', 'audit_trail', ['table_name', 'record_id'], unique=False)
    op.create_index(op.f('ix_audit_trail_entry_uid'), 'audit_trail', ['entry_uid'], unique=True)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cost_centre', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fiscal_year', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('cin', sa.String(length=21), nullable=True),
    sa.Column('tan', sa.String(length=10), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=4), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('logo_path', sa.String(length=300), nullable=True),
    sa.Column('fiscal_year_start', sa.String(length=5), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('date_format', sa.String(length=20), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('reg_date', sa.Date(), nullable=True),
    sa.Column('brand_primary_color', sa.String(length=7), nullable=True),
    sa.Column('brand_secondary_color', sa.String(length=7), nullable=True),
    sa.Column('invoice_footer_text', sa.Text(), nullable=True),
    sa.Column('subscription_plan', sa.String(length=20), nullable=True),
    sa.Column('subscription_expires', sa.Date(), nullable=True),
    sa.Column('msme_udyam_no', sa.String(length=30), nullable=True),
    sa.Column('msme_payment_days', sa.Integer(), nullable=True),
    sa.Column('einvoice_enabled', sa.Boolean(), nullable=True),
    sa.Column('eway_bill_enabled', sa.Boolean(), nullable=True),
    sa.Column('eway_bill_threshold', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_setup_done', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_centres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('manager', sa.String(length=100), nullable=True),
    sa.Column('budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['cost_centres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=True),
    sa.Column('is_base', sa.Boolean(), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('dead_letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_time',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_code', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_code')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_from_currency'), 'exchange_rates', ['from_currency'], unique=False)
    op.create_index(op.f('ix_exchange_rates_to_currency'), 'exchange_rates', ['to_currency'], unique=False)
    op.create_table('fiscal_years',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=7), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('gst_registrations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('trade_name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('state_code', sa.String(length=4), nullable=False),
    sa.Column('reg_type', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('reg_date', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin')
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_keys_key'), 'idempotency_keys', ['key'], unique=True)
    op.create_table('integration_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'cancelled', name='orderstatus'), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_table('org_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=4), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('party_type', sa.String(length=20), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=4), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_code'), 'parties', ['code'], unique=True)
    op.create_table('reporting_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('can_post', sa.Boolean(), nullable=True),
    sa.Column('can_approve', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('can_export', sa.Boolean(), nullable=True),
    sa.Column('can_admin', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('can_view_reports', sa.Boolean(), nullable=True),
    sa.Column('can_manage_masters', sa.Boolean(), nullable=True),
    sa.Column('module_access_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sms_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_code', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=160), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_code')
    )
    op.create_table('stock_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['stock_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stock_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('unit_type', sa.String(length=20), nullable=True),
    sa.Column('base_symbol', sa.String(length=10), nullable=True),
    sa.Column('factor', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('tds_challans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challan_no', sa.String(length=30), nullable=False),
    sa.Column('bsr_code', sa.String(length=10), nullable=True),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('deductee_name', sa.String(length=200), nullable=False),
    sa.Column('deductee_pan', sa.String(length=10), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('surcharge', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cess', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('quarter', sa.String(length=5), nullable=True),
    sa.Column('fy', sa.String(length=7), nullable=True),
    sa.Column('deposited', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challan_no')
    )
    op.create_table('voucher_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('affects_stock', sa.Boolean(), nullable=True),
    sa.Column('affects_bank', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('auto_number', sa.Boolean(), nullable=True),
    sa.Column('current_seq', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('event_code', sa.String(length=50), nullable=False),
    sa.Column('secret_token', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_center_loads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workcenter_id', sa.Integer(), nullable=False),
    sa.Column('load', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('trigger_event', sa.String(length=50), nullable=False),
    sa.Column('condition_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_first_login', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=128), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('password_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_app_users_username'), 'app_users', ['username'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_ref', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_kb', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('parsed_fields', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('linked_party_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=50), nullable=True),
    sa.Column('upload_date', sa.Date(), nullable=True),
    sa.Column('extraction_method', sa.String(length=30), nullable=True),
    sa.Column('pqc_signature', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linked_party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_index(op.f('ix_documents_doc_ref'), 'documents', ['doc_ref'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('doj', sa.Date(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('pf_no', sa.String(length=20), nullable=True),
    sa.Column('esic_no', sa.String(length=20), nullable=True),
    sa.Column('bank_account_no', sa.String(length=30), nullable=True),
    sa.Column('ifsc_code', sa.String(length=15), nullable=True),
    sa.Column('gross_salary', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('basic_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hra_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('father_name', sa.String(length=150), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('work_email', sa.String(length=100), nullable=True),
    sa.Column('work_location', sa.String(length=100), nullable=True),
    sa.Column('epf_enabled', sa.Boolean(), nullable=True),
    sa.Column('esi_enabled', sa.Boolean(), nullable=True),
    sa.Column('pt_enabled', sa.Boolean(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('payment_mode', sa.String(length=50), nullable=True),
    sa.Column('conveyance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('portal_access', sa.Boolean(), nullable=True),
    sa.Column('uan_no', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_emp_code'), 'employees', ['emp_code'], unique=True)
    op.create_table('ledgers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('nature', sa.String(length=2), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('opening_type', sa.String(length=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('is_bank', sa.Boolean(), nullable=True),
    sa.Column('is_cash', sa.Boolean(), nullable=True),
    sa.Column('bank_account_no', sa.String(length=30), nullable=True),
    sa.Column('ifsc_code', sa.String(length=15), nullable=True),
    sa.Column('is_tax_ledger', sa.Boolean(), nullable=True),
    sa.Column('tax_type', sa.String(length=20), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('tax_section', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['account_groups.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledgers_code'), 'ledgers', ['code'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('manager', sa.String(length=100), nullable=True),
    sa.Column('cost_centre_id', sa.Integer(), nullable=True),
    sa.Column('budgeted_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('billed_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('completion_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cost_centre_id'], ['cost_centres.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_table('sales_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('hsn_sac', sa.String(length=10), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('mrp', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reorder_level', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reorder_qty', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('current_stock', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('valuation_method', sa.String(length=10), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('warehouse', sa.String(length=100), nullable=True),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('rack', sa.String(length=50), nullable=True),
    sa.Column('bin_location', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['stock_groups.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['stock_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_items_code'), 'stock_items', ['code'], unique=True)
    op.create_table('txn_number_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voucher_type_code', sa.String(length=10), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('suffix', sa.String(length=10), nullable=True),
    sa.Column('start_seq', sa.Integer(), nullable=True),
    sa.Column('current_seq', sa.Integer(), nullable=True),
    sa.Column('padding', sa.Integer(), nullable=True),
    sa.Column('reset_period', sa.String(length=10), nullable=True),
    sa.Column('fy_label', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['voucher_type_code'], ['voucher_types.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('action_config_json', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['workflow_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('record_type', sa.String(length=30), nullable=True),
    sa.Column('record_id', sa.String(length=50), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=True),
    sa.Column('log_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['workflow_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('approver_user_id', sa.Integer(), nullable=True),
    sa.Column('approver_role_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['approver_user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycle_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('counted_quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixed_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('salvage_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('useful_life_yrs', sa.Integer(), nullable=True),
    sa.Column('depreciation_method', sa.String(length=10), nullable=True),
    sa.Column('wdv_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('accumulated_dep', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('book_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('serial_no', sa.String(length=100), nullable=True),
    sa.Column('is_disposed', sa.Boolean(), nullable=True),
    sa.Column('disposal_date', sa.Date(), nullable=True),
    sa.Column('disposal_proceeds', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ledger_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixed_assets_asset_code'), 'fixed_assets', ['asset_code'], unique=True)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturing_bom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('components_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('performance_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['sales_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=80), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_warehouse', sa.String(length=100), nullable=False),
    sa.Column('target_warehouse', sa.String(length=100), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['stock_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_fy', sa.String(length=7), nullable=True),
    sa.Column('date_format', sa.String(length=20), nullable=True),
    sa.Column('items_per_page', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('notify_by_email', sa.Boolean(), nullable=True),
    sa.Column('notify_by_sms', sa.Boolean(), nullable=True),
    sa.Column('dashboard_layout_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voucher_no', sa.String(length=50), nullable=False),
    sa.Column('voucher_type_id', sa.Integer(), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=7), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('ref_no', sa.String(length=100), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('taxable_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('is_inter_state', sa.Boolean(), nullable=True),
    sa.Column('supply_state', sa.String(length=4), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('reversed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pqc_signature', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['reversed_by'], ['vouchers.id'], ),
    sa.ForeignKeyConstraint(['voucher_type_id'], ['voucher_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_voucher_date_type', 'vouchers', ['voucher_date', 'voucher_type_id'], unique=False)
    op.create_index('idx_voucher_fy', 'vouchers', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_vouchers_voucher_date'), 'vouchers', ['voucher_date'], unique=False)
    op.create_index(op.f('ix_vouchers_voucher_no'), 'vouchers', ['voucher_no'], unique=True)
    op.create_table('bank_reconciliations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_ledger_id', sa.Integer(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('statement_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('book_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('uncleared_deposits', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('uncleared_payments', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('bank_charges', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('interest_credited', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('adjusted_bank_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=True),
    sa.Column('auto_jv_id', sa.Integer(), nullable=True),
    sa.Column('reconciled_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auto_jv_id'], ['vouchers.id'], ),
    sa.ForeignKeyConstraint(['bank_ledger_id'], ['ledgers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('cost_centre', sa.String(length=20), nullable=True),
    sa.Column('project_code', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('amount_fc', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(debit = 0 AND credit > 0) OR (debit > 0 AND credit = 0) OR (debit = 0 AND credit = 0)', name='chk_dr_cr_exclusive'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_ledger_id'), 'transactions', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_transactions_voucher_id'), 'transactions', ['voucher_id'], unique=False)
    op.create_table('voucher_line_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('stock_item_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('hsn_sac', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_amt', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('taxable_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgst_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('igst_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cess_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['stock_units.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_line_items_voucher_id'), 'voucher_line_items', ['voucher_id'], unique=False)
    op.create_table('warehouse_sales_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_no', sa.String(length=50), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['manufacturing_bom.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_no')
    )
    op.create_table('inspection_checklists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspection_checklists')
    op.drop_table('work_orders')
    op.drop_table('warehouse_sales_facts')
    op.drop_index(op.f('ix_voucher_line_items_voucher_id'), table_name='voucher_line_items')
    op.drop_table('voucher_line_items')
    op.drop_index(op.f('ix_transactions_voucher_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_ledger_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('escalations')
    op.drop_table('bank_reconciliations')
    op.drop_index(op.f('ix_vouchers_voucher_no'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_voucher_date'), table_name='vouchers')
    op.drop_index('idx_voucher_fy', table_name='vouchers')
    op.drop_index('idx_voucher_date_type', table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_table('user_preferences')
    op.drop_table('transfer_orders')
    op.drop_table('tasks')
    op.drop_table('sales_orders')
    op.drop_table('performance_reviews')
    op.drop_table('manufacturing_bom')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_fixed_assets_asset_code'), table_name='fixed_assets')
    op.drop_table('fixed_assets')
    op.drop_table('cycle_counts')
    op.drop_table('approval_rules')
    op.drop_table('workflow_logs')
    op.drop_table('workflow_instances')
    op.drop_table('workflow_actions')
    op.drop_table('txn_number_series')
    op.drop_index(op.f('ix_stock_items_code'), table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_table('sales_quotes')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_ledgers_code'), table_name='ledgers')
    op.drop_table('ledgers')
    op.drop_index(op.f('ix_employees_emp_code'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_documents_doc_ref'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_app_users_username'), table_name='app_users')
    op.drop_table('app_users')
    op.drop_table('workflow_rules')
    op.drop_table('workflow_definitions')
    op.drop_table('work_center_loads')
    op.drop_table('webhooks')
    op.drop_table('voucher_types')
    op.drop_table('tds_challans')
    op.drop_table('system_config')
    op.drop_table('stock_units')
    op.drop_table('stock_groups')
    op.drop_table('sms_templates')
    op.drop_table('roles')
    op.drop_table('reporting_tags')
    op.drop_index(op.f('ix_parties_code'), table_name='parties')
    op.drop_table('parties')
    op.drop_table('org_locations')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('integration_tokens')
    op.drop_table('integration_logs')
    op.drop_index(op.f('ix_idempotency_keys_key'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_table('gst_registrations')
    op.drop_table('fiscal_years')
    op.drop_index(op.f('ix_exchange_rates_to_currency'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_from_currency'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_table('email_templates')
    op.drop_table('dim_time')
    op.drop_table('dim_product')
    op.drop_table('dim_customer')
    op.drop_table('dead_letters')
    op.drop_table('currencies')
    op.drop_table('cost_centres')
    op.drop_table('company')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_audit_trail_entry_uid'), table_name='audit_trail')
    op.drop_index('idx_audit_table_record', table_name='audit_trail')
    op.drop_table('audit_trail')
    op.drop_index(op.f('ix_account_groups_code'), table_name='account_groups')
    op.drop_table('account_groups')
    # ### end Alembic commands ###
