"""order_calculation_fields

Revision ID: b671feec2020
Revises: 792ff300ec7c
Create Date: 2026-04-01 01:13:04.998046

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b671feec2020"
down_revision: Union[str, None] = "792ff300ec7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    op.create_table(
        "tax_masters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "unit_masters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column(
        "orders",
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
    )
    op.add_column(
        "orders",
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
    )
    op.add_column(
        "orders",
        sa.Column("subtotal", sa.Numeric(precision=18, scale=2), nullable=False),
    )
    op.add_column(
        "orders",
        sa.Column("tax_amount", sa.Numeric(precision=18, scale=2), nullable=False),
    )
    op.add_column("orders", sa.Column("unit_id", sa.Integer(), nullable=True))
    op.add_column("orders", sa.Column("tax_id", sa.Integer(), nullable=True))
    if not is_sqlite:
        op.create_foreign_key(None, "orders", "unit_masters", ["unit_id"], ["id"])
        op.create_foreign_key(None, "orders", "tax_masters", ["tax_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    if not is_sqlite:
        op.drop_constraint(None, "orders", type_="foreignkey")
        op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "tax_id")
    op.drop_column("orders", "unit_id")
    op.drop_column("orders", "tax_amount")
    op.drop_column("orders", "subtotal")
    op.drop_column("orders", "unit_price")
    op.drop_column("orders", "quantity")
    op.drop_table("unit_masters")
    op.drop_table("tax_masters")
    # ### end Alembic commands ###
