"""add_journal_entries

Revision ID: f3d0ba196e04
Revises: b671feec2020
Create Date: 2026-04-01 01:24:13.288044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d0ba196e04'
down_revision: Union[str, None] = 'b671feec2020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ledger_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_ledger_id'), 'journal_entries', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_reference'), 'journal_entries', ['reference'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entries_reference'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_ledger_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
